name: ptt
channels:
  - conda-forge
dependencies:
  - python=3.9
  - movingpandas
  - cartopy
  - hvplot
  - geopandas
  - geoviews
  - geopy
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - seaborn
  - shapely
  - stonesoup
